---
title: "Experiments with Fire and Caribou"
author: "Steve Cumming"
date: "April 13, 2017"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r loadShp, echo=FALSE}
library(magrittr)
library(rgdal)
library(SpaDES)

baseDir <- file.path("inputs")
cacheLoc<-file.path("cache")

paths <- list(inputPath = "inputs",
              cachePath = cacheLoc,
              outputPath = "outputs")
studyArea <- "LARGE" # can be SMALL, MEDIUM, LARGE, FULL
#saveDir<-setwd("/Users/stevec/Dropbox/Courses/7043H17/Lab")
#dataDir<-file.path("/Users/stevec/Dropbox/SpaDES/Data/LandWEB/shp")
#dataDir<-file.path("/Users/stevec/Dropbox/SpaDES/Data/LandWEB/shp")
#savedDir<-setwd(dataDir)
#shape <- readOGR(dsn = ".", layer = "ltfrcycles3")

paths <- list(inputPath = "inputsLandWeb",
              cachePath = cacheLoc)
source("inputMaps.R")
paths <- list(inputPath = baseDir,
              cachePath = cacheLoc,
              outputPath = "outputs")

studyArea <- shpStudyRegion 
studyArea <- studyArea[studyArea$ECOREGION == "87",]

Plot(studyArea, new = TRUE)
```

## Classification and Patch Metrics

Now in this excercise we build a map classifier and then use package _SDMTools_ to generate patch metrics.

The function we will use is SDMTool::ClassStat()

```{r Data2ModelsPlusPatches, echo=TRUE}
library(SpaDES)
library(igraph)
library(spatial.tools)
library(magrittr) #implements pipes as %>%
library(archivist)
library(memoise)
library(raster)
library(SDMTools) #NOTE NEW

#there is supposed to be someway to get simInit to read this, too, but the method are undocumented and I can not get them to work...s'matter of specifying the names arguments of readOGR, and also in what environment or package to look for the memoised version we just created here.
#if(!exists("readOGRmem")) readOGRmem <- memoise(readOGR)


# Fire database
  dsnPath <- checkPath(file.path(baseDir, "CanadianNationalFireDatabase", "NFDB_point"),  create = TRUE) %>% 
    file.path(., "FirePoints.zip")
  pointDataFilename <- dir(file.path(paths$inputPath), pattern = "NFDB_point", full.names = TRUE)
  
  if (length(pointDataFilename) == 0) {
    download.file("http://cwfis.cfs.nrcan.gc.ca/downloads/nfdb/fire_pnt/current_version/NFDB_point.zip", 
                  destfile = dsnPath, method = "auto")
    unzip(dsnPath, exdir = paths$inputPath)
    file.remove(dsnPath)
  }
  
  pointDataFilename <- dir(file.path(paths$inputPath), pattern = "NFDB_point", 
                           full.names = TRUE)
  pointDataFilename <- pointDataFilename[grep(pattern = ".shp$", pointDataFilename)]
  
  #somebody don't like ~stevec. ahem, readOGR,
  if (!exists("firePointsInput")){
    library(sf)
    loadShapefile <- function(filename) {
      s1 <- st_read(filename, stringsAsFactors=FALSE);
      as(s1, "Spatial")
    }
    firePointsInput <- Cache(loadShapefile, pointDataFilename, cacheRepo = paths$cachePath)
    # firePointsInput<-Cache(shapefile, asPath(pointDataFilename), 
    #                          cacheRepo = paths$cachePath)
  }

## LCC05
  if (!file.exists(file.path(paths$inputPath, "LandCoverOfCanada2005_V1_4"))) {
    dir.create(file.path(paths$inputPath, "LandCoverOfCanada2005_V1_4"))
  }
  filename <- "LCC2005_V1_4a.tif"
  remoteFilename <- "LandCoverOfCanada2005_V1_4.zip"
  localPath <- file.path(paths$inputPath, "LandCoverOfCanada2005_V1_4", filename)
  if (!file.exists(localPath)) {
    download.file(file.path("ftp://ftp.ccrs.nrcan.gc.ca/ad/NLCCLandCover/LandcoverCanada2005_250m", remoteFilename), 
                  destfile = file.path(dirname(localPath), remoteFilename) , 
                  mode="wb")
    unzip(file.path(dirname(localPath), remoteFilename), exdir = dirname(localPath))#, files="LandCoverOfCanada2005_V1_4/LCC2005_V1_4a.tif")
    file.remove(file.path(dirname(localPath), remoteFilename))
  }
  
  
  inputs <- data.frame(file = c(file.path("age", "age.tif"), 
                                file.path("LandCoverOfCanada2005_V1_4", "LCC2005_V1_4a.tif"),
                                file.path("spread_firesize_curves.csv"),
                                file.path("FiresN1000MinFiresSize2NoLakes.csv")),
                       fun = c("raster", "raster", "read.csv", "read.csv"),
                       package = c("raster", "raster", "utils", "utils"),
                       objectName = c("ageMapInit", "vegMapInit", "spreadCalibrationTable", "cTable2"))
  
  times <- list(start = 0, end = 30, timeunit = "year")
  
  plotInit <- NA #times$start+1
  defaultInterval <- 1
  defaultInitialSaveTime <- NA
  
  parameters <- list(
    .globals = list(neighbours = 8),
    .progress = list(type = NA, interval = 1), #was type="graphical"
    scfmCrop = list(useCache = TRUE, .useCache = "init"),
    scfmLandcoverInit = list(useCache = TRUE, .useCache = "init"),
    scfmRegime = list(fireEpoch = c(1971, 2010), fireCause =c("L")),
    ageModule = list(
      initialAge = 100, 
      maxAge = 200, 
      returnInterval = defaultInterval, 
      startTime = times$start,
      .plotInitialTime = times$start,
      .plotInterval = defaultInterval,
      .saveInitialTime = defaultInitialSaveTime, 
      .saveInterval=defaultInterval),
    scfmIgnition = list(
      pIgnition = 0.0002, 
      returnInterval = defaultInterval, 
      startTime = times$start,
      .plotInitialTime = NA,
      .plotInterval = defaultInterval,
      .saveInitialTime = defaultInitialSaveTime, 
      .saveInterval = defaultInterval),
    scfmEscape = list(
      p0 = 0.1, 
      returnInterval = defaultInterval, 
      startTime = times$start,
      .plotInitialTime = NA,
      .plotInterval = defaultInterval,
      .saveInitialTime = defaultInitialSaveTime, 
      .saveInterval = defaultInterval),
    scfmSpread = list(
      pSpread = 0.235, 
      returnInterval = defaultInterval, 
      startTime = times$start,
      .plotInitialTime = times$start,
      .plotInterval = defaultInterval,
      .saveInitialTime = defaultInitialSaveTime, 
      .saveInterval = defaultInterval),
    classifyAge = list(
      startTime = times$start,
      returnInterval = 5,
      .plotInitialTime = NA,#times$start,
      .plotInterval = 5,
      howOldIsOld = 120
    )
  )
  #
  #modules<-list("scfmParent")
  modules <- list("scfmCrop","scfmLandcoverInit", "scfmRegime", "scfmDriver",
                  "ageModule", "scfmIgnition", "scfmEscape", "scfmSpread", "classifyAge") # "caribou"
              
  paths[["modulePath"]] <- "modules"
  
  
  shape <- Cache(shapefile, file.path(baseDir,"shpLandWEB.shp"))
  studyArea <- shape[shape$ECOREGION == 87,] #we have chosen Athabasca Plains in northern SK
                                             #we happen to know the numeric code is 87 (easier to type)
  Plot(studyArea)
  
  objects <- list(
    firePointsInput = firePointsInput,
    studyArea = studyArea,
    cacheLoc = cacheLoc
  )
  
  try(rm(mySim))
  dev()
  mySim <- simInit(times=times, params=parameters, modules=modules,paths=paths, objects=objects,inputs=inputs) 
  tmpSim<- spades(mySim,debug=TRUE)#, .plotInitialTime = NA)
```
