defineModule(sim, list(
  name = "scfmSpread",
  description = "model fire spread",
  keywords = c("fire", "spread", "scfm"),
  authors = c(
    person("Steve", "Cumming", email = "stevec@sbf.ulaval.ca", role = "aut"),
    person("Ian", "Eddy", email = "ian.eddy@nrcan-rncan.gc.ca", role = "aut"),
    person("Alex M", "Chubaty", email = "achubaty@for-cast.ca", role = "ctb")
  ),
  childModules = character(),
  version = numeric_version("2.0.0"),
  spatialExtent = raster::extent(rep(NA_real_, 4)),
  timeframe = as.POSIXlt(c(NA, NA)),
  timeunit = "year",
  citation = list("citation.bib"),
  documentation = list("README.txt", "scfmSpread.Rmd"),
  reqdPkgs = list("data.table", "fpCompare", "magrittr", "raster",
                  "PredictiveEcology/LandR@development",
                  "PredictiveEcology/reproducible@development",
                  "PredictiveEcology/scfmutils (>= 0.0.5)",
                  "PredictiveEcology/SpaDES.tools (>= 1.0.2.9001)"),
  parameters = rbind(
    defineParameter("neighbours", "numeric", 8, NA, NA,
                    desc = "Number of immediate cell neighbours"),
    defineParameter("pSpread", "numeric", 0.23, 0, 1,
                    desc = "default spread probability if `scfmDriverPars` is not supplied."),
    defineParameter("returnInterval", "numeric", 1.0, NA, NA,
                    desc = "Time interval between burn events"),
    defineParameter("startTime", "numeric", start(sim), NA, NA,
                    desc = "Simulation time at which to initiate burning"),
    defineParameter(".plotInitialTime", "numeric", start(sim, "year") + 1, NA, NA,
                    desc = "This describes the simulation time at which the first plot event should occur"),
    defineParameter(".plotInterval", "numeric", 1, NA, NA,
                    desc = "This describes the simulation time at which the first plot event should occur"),
    defineParameter(".useCache", "character", c(".inputObjects"), NA, NA,
                    desc = "Can be names of events or the whole module name; these will be cached by SpaDES")
  ),
  inputObjects = bindrows(
    expectsInput("fireRegimeRas", "RasterLayer", desc = "raster with fire regimes from `fireRegimePolys`."),
    expectsInput("flammableMap", "RasterLayer", desc = "binary map of landscape flammability"),
    expectsInput("landscapeAttr", "list",
                 desc = "list generated by `scfmLandcoverInit` with attributes for each polygon"),
    expectsInput("rasterToMatch", "RasterLayer",
                 desc = "template raster for raster GIS operations. Must be supplied by user."),
    expectsInput("scfmDriverPars", "list", desc = "fire modules' parameters"),
    expectsInput("spreadState", "data.table", desc = "see `SpaDES.tools::spread2`"),
    expectsInput("studyArea", "SpatialPolygonsDataFrame",
                 desc = "Polygon to use as the simulation study area."),
    expectsInput("studyAreaReporting", "sf",
                 desc = paste("multipolygon (typically smaller/unbuffered than `studyArea`)",
                              "to use for plotting/reporting."))
  ),
  outputObjects = bindrows(
    createsOutput("burnDT", "data.table", desc = "data table with pixel IDs of most recent burn"),
    createsOutput("burnMap", "RasterLayer", desc = "cumulative burn map"),
    createsOutput("burnSummary", "data.table", desc = "describes details of all burned pixels"),
    createsOutput("pSpread", "RasterLayer", desc = "spread probability applied to flammabiliy Map"),
    createsOutput("rstCurrentBurn", "RasterLayer", desc = "annual burn map")
  )
))

## event types
#   - type `init` is required for initialiazation

doEvent.scfmSpread = function(sim, eventTime, eventType, debug = FALSE) {
  switch(
    eventType,
    init = {
      sim <- Init(sim)

      # schedule future event(s)
      sim <- scheduleEvent(sim, P(sim)$startTime, "scfmSpread", "burn", 7.5)

      if ("screen" %in% P(sim)$.plots) {
        sim <- scheduleEvent(sim, P(sim)$.plotInitialTime, "scfmSpread", "plot", eventPriority = .last())
      }
    },
    burn = {
      if (!is.null(sim$spreadState)) {

        if (NROW(sim$spreadState[state == "activeSource"]) > 0) {
          sim <- Burnemup(sim) ## fire sizes recorded in  sim$burnSummary
        } else {
          ## make sure to record fires that did not escape/spread
          tempDT <- countBurnedPixelsInSAR(sim$spreadState)
          tempDT$year <- time(sim)
          tempDT[, areaBurned := N * sim$landscapeAttr[[1]]$cellSize]
          tempDT$PolyID <- if (length(tempDT$initialPixels) > 0) sim$fireRegimeRas[tempDT$initialPixels] else NA_integer_
          setnames(tempDT, c("initialPixels"), c("igLoc"))
          sim$burnSummary <- rbind(sim$burnSummary, tempDT)
        }
      }
      sim <- scheduleEvent(sim, time(sim) + P(sim)$returnInterval, "scfmSpread", "burn", eventPriority = 7.5)
    },
    plot = {
      if (!is.null(sim$rstCurrentBurn)) {
        Plot(sim$rstCurrentBurn, new = TRUE, col = c("grey", "red"),
             title = paste0("annual burn: year", time(sim)))
        Plot(sim$burnMap, title = "Cumulative Burn", addTo = TRUE)
      }
      sim <- scheduleEvent(sim, time(sim) + P(sim)$.plotInterval, "scfmSpread", "plot", eventPriority = 8)
    },
    warning(paste("Undefined event type: '", events(sim)[1, "eventType", with = FALSE],
                  "' in module '", events(sim)[1, "moduleName", with = FALSE], "'", sep = ""))
  )
  return(invisible(sim))
}

Init <- function(sim) {
  compareGeom(sim$rasterToMatch, sim$fireRegimeRas)
  compareGeom(sim$fireRegimeRas, sim$flammableMap)
  tmpRas <- postProcess(sim$rasterToMatch, studyArea = sim$studyAreaReporting)
  mod$pixInSAR <- which(!is.na(as.vector(tmpRas)))

  ## better to use fireRegimeRas than flammableMap, or burnMap inherits attributes
  sim$burnMap <- rast(sim$fireRegimeRas)
  sim$burnMap[!is.na(sim$flammableMap[])] <- 0
  sim$burnMap[sim$flammableMap[] %==% 0] <- NA
  if ("scfmDriverPars" %in% ls(sim)) {
    if (length(sim$scfmDriverPars) > 1) {
      pSpread <- rast(sim$flammableMap)
      for (x in names(sim$scfmDriverPars)) {
        pSpread[sim$landscapeAttr[[x]]$cellsByZone] <- sim$scfmDriverPars[[x]]$pSpread
      }
      pSpread <- pSpread * sim$flammableMap
    } else {
      pSpread <- sim$flammableMap * sim$scfmDriverPars[[1]]$pSpread
    }
  } else {
    pSpread <- P(sim)$pSpread * sim$flammableMap
  }
  sim$pSpread <- pSpread
  #Create empty data table to store each year's burn data
  sim$burnSummary <- data.table(igLoc = integer(0),
                                grp = integer(0),
                                N = numeric(0),
                                year = numeric(0),
                                areaBurned = numeric(0),
                                PolyID = integer(0))

  sim$rstCurrentBurn <- rast(sim$fireRegimeRas)
  sim$rstCurrentBurn[sim$flammableMap[] %==% 1] <- 0 # reset annual burn
  sim$rstCurrentBurn[sim$flammableMap[] %==% 0] <- NA # might have to ignore warnings

  return(invisible(sim))
}

countBurnedPixelsInSAR <- function(burnDT) {
  tempDT <- copy(burnDT)

  ## grp 1: pixels from fires ignited in SAR & spread in SAR
  ## grp 2: pixels from fires ignited in SAR & spread outside SAR
  ## grp 3: pixels from fires ignited outside SAR & spread in SAR
  ## grp 4: pixels from fires ignited outside SAR & spread outside SAR

  tempDT[(initialPixels %in% mod$pixInSAR) & (pixels %in% mod$pixInSAR), grp := 1L]
  tempDT[(initialPixels %in% mod$pixInSAR) & !(pixels %in% mod$pixInSAR), grp := 2L]
  tempDT[!(initialPixels %in% mod$pixInSAR) & (pixels %in% mod$pixInSAR), grp := 3L]
  tempDT[!(initialPixels %in% mod$pixInSAR) & !(pixels %in% mod$pixInSAR), grp := 4L]
  tempDT <- tempDT[, .N, by = c("initialPixels", "grp")]

  return(tempDT)
}

## name 'Burnemup' is a homage to Walters and Hillborne
Burnemup <- function(sim) {
  # maxSizes <- unlist(lapply(sim$scfmDriverPars, function(x) x$maxBurnCells))
  # activeLoci <- unique(sim$spreadState$initialLocus) # indices[sim$spreadState$active]
  #we prevent multiple ignitions, which shouldn't happen anyway.

  threadsDT <- data.table::getDTthreads()
  setDTthreads(1)
  on.exit({setDTthreads(threadsDT)}, add = TRUE)

  sim$burnDT <- SpaDES.tools::spread2(sim$flammableMap,
                                      start = sim$spreadState,
                                      spreadProb = sim$pSpread,
                                      #spreadState = sim$spreadState,
                                      directions = P(sim)$neighbours,
                                      # maxSize = maxSizes,  #not sure this works
                                      asRaster = FALSE)

  sim$rstCurrentBurn <- raster(sim$fireRegimeRas) ## use fireRegimeRas as template
  sim$rstCurrentBurn[sim$flammableMap[] %==% 1] <- 0 ## reset annual burn
  sim$rstCurrentBurn[sim$flammableMap[] %==% 0] <- NA ## might have to ignore warnings.

  sim$rstCurrentBurn[sim$burnDT$pixels] <- 1 ## update annual burn
  sim$rstCurrentBurn@data@attributes <- list("Year" == time(sim))

  sim$burnMap[sim$burnDT$pixels] <- sim$burnMap[sim$burnDT$pixels] + 1 ## update cumulative burn

  ## get fire year, pixels burned, area burned, poly ID of all burned pixels in studyAreaReporting
  tempDT <- countBurnedPixelsInSAR(sim$burnDT)
  tempDT$year <- time(sim)
  tempDT$areaBurned <- tempDT$N * sim$landscapeAttr[[1]]$cellSize
  tempDT$PolyID <- if (length(tempDT$initialPixels) > 0) sim$fireRegimeRas[tempDT$initialPixels] else NA_integer_
  setnames(tempDT, c("initialPixels"), c("igLoc"))
  sim$burnSummary <- rbind(sim$burnSummary, tempDT)
  return(invisible(sim))
}

.inputObjects <- function(sim) {
  if (!suppliedElsewhere("fireRegimeRas", sim)) {
    stop("you should run scfmLandCoverInit")
  }

  if (!suppliedElsewhere("flammableMap", sim)) {
    message("you should run scfmIgnition with scfmLandcoverInit")
    flammableMap <- raster(sim$rasterToMatch)
    vals <- sample(x = 0:1, size = ncell(sim$rasterToMatch), replace = TRUE)
    sim$flammableMap <- setValues(flammableMap, vals)
  }

  if (!suppliedElsewhere("studyAreaReporting", sim)) {
    message("'studyAreaReporting' was not provided by user. Using the same as 'studyArea'.")
    sim$studyAreaReporting <- sim$studyArea
  }
  return(sim)
}
